/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-08-10 20:33:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>About Page</title>\n");
      out.write("<link\n");
      out.write("\thref='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic|Source+Code+Pro:400,700'\n");
      out.write("\trel='stylesheet' type='text/css'>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("@import\n");
      out.write("\turl(https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700);\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\twidth: 80%;\n");
      out.write("\tborder: 20px solid #bdc3c7;\n");
      out.write("\tfont-family: 'Source Sans Pro', sans-serif;\n");
      out.write("\tpadding: 20px;\n");
      out.write("\tmargin: 20px auto;\n");
      out.write("\tmax-width: 700px;\n");
      out.write("\tbackground:\n");
      out.write("\t\turl(https://www2.eurosciencejobs.com/images/esj_site_background.jpg)\n");
      out.write("\t\tno-repeat center center fixed;\n");
      out.write("\t-webkit-background-size: cover;\n");
      out.write("\t-moz-background-size: cover;\n");
      out.write("\t-o-background-size: cover;\n");
      out.write("\tbackground-size: cover;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".post {\n");
      out.write("\tmargin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".date {\n");
      out.write("\tcolor: #f149f1;\n");
      out.write("\tletter-spacing: 0.2rem;\n");
      out.write("\ttext-transform: uppercase;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".quote {\n");
      out.write("\tborder-left: 5px solid #bdc3c7;\n");
      out.write("\tpadding-left: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h2 {\n");
      out.write("\tfont-size: 2.0rem;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\tcolor: #2c3e50;\n");
      out.write("}\n");
      out.write("\n");
      out.write("hr {\n");
      out.write("\tborder: 0;\n");
      out.write("\theight: 0;\n");
      out.write("\tborder-top: 1px solid rgba(0, 0, 0, 0.1);\n");
      out.write("\tborder-bottom: 1px solid rgba(255, 255, 255, 0.3);\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"post\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"date\">November 23 2015</div>\n");
      out.write("\t\t<h2>About Online BOI</h2>\n");
      out.write("\n");
      out.write("\t\t<p class=\"quote\">Bank of India is India's largest bank with a\n");
      out.write("\t\t\tnetwork of over 15000 branches and 5 associate banks located even in\n");
      out.write("\t\t\tthe remotest parts of India. Bank of India (BOI) offers a wide range\n");
      out.write("\t\t\tof banking products and services to corporate and retail customers.</p>\n");
      out.write("\n");
      out.write("\t\t<p>OnlineBOI is the Internet banking portal for Bank of India. The\n");
      out.write("\t\t\tportal provides anywhere, anytime, online access to accounts for\n");
      out.write("\t\t\tBank's Retail and Corporate customers. The application is developed\n");
      out.write("\t\t\tusing the latest cutting edge technology and tools. The\n");
      out.write("\t\t\tinfrastructure supports unified, secure access to banking services\n");
      out.write("\t\t\tfor accounts in over 15,000 branches across India.</p>\n");
      out.write("\n");
      out.write("\t\t<h2>Who can avail Corporate Internet Banking?</h2>\n");
      out.write("\n");
      out.write("\t\t<p>For the purpose of Internet Banking, all non-individual\n");
      out.write("\t\t\tcustomers, viz., small business enterprises, firms, trusts,\n");
      out.write("\t\t\tinstitutions, Government organizations or large conglomerates are\n");
      out.write("\t\t\ttreated as Corporates. So irrespective of whether you are sole\n");
      out.write("\t\t\tproprietor or partner of a small firm or managing the accounts of a\n");
      out.write("\t\t\tlarge corporate or Government department with complex financial\n");
      out.write("\t\t\trequirements, BOI has the right solution for you under Corporate\n");
      out.write("\t\t\tInternet Banking.</p>\n");
      out.write("\t\t<hr>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- <hr> -->\n");
      out.write("\n");
      out.write("\t<div class=\"post\">\n");
      out.write("\t\t<div class=\"date\">December 11 2015</div>\n");
      out.write("\t\t<h2>Retail Internet Banking</h2>\n");
      out.write("\n");
      out.write("\t\t<p class=\"quote\">The Retail Internet Banking offers a plethora of\n");
      out.write("\t\t\tproducts and services, to cater to all your banking demands online:\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li>Transfer funds to own and third party accounts A suite of\n");
      out.write("\t\t\t\tcompletely online deposit products (Fixed, Recurring, Flexi, Tax\n");
      out.write("\t\t\t\tSaving etc.) Airline, Rail, Bus and hotel ticket booking Online\n");
      out.write("\t\t\t\tShopping and instant recharge features.</li>\n");
      out.write("\t\t\t<li>IMPS Funds Transfer Western Union Service Credit beneficiary\n");
      out.write("\t\t\t\taccounts using RTGS/NEFT feature Generate account statements Setup\n");
      out.write("\t\t\t\tStanding Instructions and Scheduling payments Configure profile\n");
      out.write("\t\t\t\tsettings E- Tax for online tax payment E - Pay for automatic bill\n");
      out.write("\t\t\t\tpayments Avail DEMAT and IPO services Pay bill of Visa Credit Card\n");
      out.write("\t\t\t\tissued by any Bank. Other Value added Services</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t</p>\n");
      out.write("\t\t<hr>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"post\">\n");
      out.write("\t\t<h2>Corporate Internet Banking</h2>\n");
      out.write("\t\t<p class=\"quote\">Bank of India offers world class Internet Banking\n");
      out.write("\t\t\tservices to its Corporate Customers through the portal\n");
      out.write("\t\t\twww.onlinesbi.com. The Corporate Internet Banking (CINB) facility of\n");
      out.write("\t\t\tBOI enables the corporate customer to carry out banking activities\n");
      out.write("\t\t\tanywhere and anytime aided with the power and convenience of the\n");
      out.write("\t\t\tinternet.</p>\n");
      out.write("\n");
      out.write("\t\t<p>Transfer funds to own and third party accounts A suite of\n");
      out.write("\t\t\tcompletely online deposit products (Fixed, Recurring, Flexi, Tax\n");
      out.write("\t\t\tSaving etc.) Airline, Rail, Bus and hotel ticket booking Online\n");
      out.write("\t\t\tShopping and instant recharge features</p>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"panel-footer\">\n");
      out.write("\t\tClick Here To Go Back <input type=\"button\" value=\"Go To Home\"\n");
      out.write("\t\t\tonclick=\"window.location.href='afterloginHomePage';return false;\"></input>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
